package com.yongaishide.chaosworld.block.entity.pattern;

import com.yongaishide.chaosworld.api.multiblock.MultiblockPattern;
import com.yongaishide.chaosworld.block.MultiblockBlocks;
import net.minecraft.network.chat.Component;

import net.minecraft.world.level.block.state.BlockState;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

public class StellarNexusPatternFactory {

    public static Map<Character, BlockState> getDefaultCreativeStates() {
        Map<Character, BlockState> map = new HashMap<>();
        map.put('B', MultiblockBlocks.ENTROPY_SINGULARITY_CASING.get().defaultBlockState());
        map.put('C', MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get().defaultBlockState());
        map.put('D', MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get().defaultBlockState());
        map.put('E', MultiblockBlocks.STELLAR_FIELD_GENERATOR_T3.get().defaultBlockState());
        map.put('F', MultiblockBlocks.ENTROPY_SINGULARITY_CASING.get().defaultBlockState());
        map.put('G', MultiblockBlocks.ENTROPY_SINGULARITY_CASING.get().defaultBlockState());
        return map;
    }

    public static MultiblockPattern getPattern() {
        // Build the pattern using the new 35x34x35 structure
        MultiblockPattern.Builder builder = new MultiblockPattern.Builder();
        builder.controllerChar('H');

        builder.layer(new String[]{
            "                                  ^",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "              BBBBBBBBB            ",
            "                 B B               ",
            "              BBBBBBBBB            ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                CCCCC              ",
            "               CCBCBCC             ",
            "           BBBBCBBCBBCBBBB         ",
            "               CCCCCCC             ",
            "           BBBBCBBCBBCBBBB         ",
            "               CCBCBCC             ",
            "                CCCCC              ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "                  C                ",
            "               CCCCCCC             ",
            "              CC     CC            ",
            "              C  DDD  C            ",
            "         BBB  C DEEED C  BBB       ",
            "            CCC DEEED CCC          ",
            "         BBB  C DEEED C  BBB       ",
            "              C  DDD  C            ",
            "              CC     CC            ",
            "               CCCCCCC             ",
            "                  C                ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "                  C                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "        BB                 BB      ",
            "          CC             CC        ",
            "        BB                 BB      ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  C                ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                BBBBB              ",
            "                  C                ",
            "                  E                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "        B                   B      ",
            "       BB                   BB     ",
            "        BCEE             EECB      ",
            "       BB                   BB     ",
            "        B                   B      ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  E                ",
            "                  C                ",
            "                BBBBB              ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "               FDDEDDF             ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "         F                 F       ",
            "         D                 D       ",
            "      BB D                 D BB    ",
            "        CE                 EC      ",
            "      BB D                 D BB    ",
            "         D                 D       ",
            "         F                 F       ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "               FDDEDDF             ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                BBBBB              ",
            "                  C                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "      B                       B    ",
            "     BB                       BB   ",
            "      BCE                   ECB    ",
            "     BB                       BB   ",
            "      B                       B    ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  C                ",
            "                BBBBB              ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "               FDDEDDF             ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "       F                     F     ",
            "       D                     D     ",
            "    BB D                     D BB  ",
            "      CE                     EC    ",
            "    BB D                     D BB  ",
            "       D                     D     ",
            "       F                     F     ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "               FDDEDDF             ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                  C                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    B                           B  ",
            "     CE                       EC   ",
            "    B                           B  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  C                ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "   BB                           BB ",
            "     CE                       EC   ",
            "   BB                           BB ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                  C                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "   B                             B ",
            "    C                           C  ",
            "   B                             B ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  C                ",
            "                 B B               ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                  C                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "   B                             B ",
            "    C                           C  ",
            "   B                             B ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  C                ",
            "                 B B               ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "               BBBBBBB             ",
            "                 B B               ",
            "               CCCCCCC             ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    C                           C  ",
            "    C                           C  ",
            "  BBC                           CBB",
            "    C                           C  ",
            "  BBC                           CBB",
            "    C                           C  ",
            "    C                           C  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "               CCCCCCC             ",
            "                 B B               ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BBGGGGGBB            ",
            "                CCCCC              ",
            "              CC     CC            ",
            "                                   ",
            "                                   ",
            "         F                 F       ",
            "                                   ",
            "       F                     F     ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    C                           C  ",
            "    C                           C  ",
            "   C                             C ",
            "  BC                             CB",
            "   C                             C ",
            "  BC                             CB",
            "   C                             C ",
            "    C                           C  ",
            "    C                           C  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "       F                     F     ",
            "                                   ",
            "         F                 F       ",
            "                                   ",
            "                                   ",
            "              CC     CC            ",
            "                CCCCC              ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BGGGGGGGB            ",
            "               CCBCBCC             ",
            "              C  DDD  C            ",
            "                                   ",
            "        B                   B      ",
            "         D                 D       ",
            "      B                       B    ",
            "       D                     D     ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    C                           C  ",
            "   C                             C ",
            "   C                             C ",
            "  BBD                           DBB",
            "   CD                           DC ",
            "  BBD                           DBB",
            "   C                             C ",
            "   C                             C ",
            "    C                           C  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "       D                     D     ",
            "      B                       B    ",
            "         D                 D       ",
            "        B                   B      ",
            "                                   ",
            "              C  DDD  C            ",
            "               CCBCBCC             ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BGGBBBGGB            ",
            "           BBBBCBBCBBCBBBB         ",
            "         BBB  C DEEED C  BBB       ",
            "        BB                 BB      ",
            "       BB                   BB     ",
            "      BB D                 D BB    ",
            "     BB                       BB   ",
            "    BB D                     D BB  ",
            "    B                           B  ",
            "   BB                           BB ",
            "   B                             B ",
            "   B                             B ",
            "  BBC                           CBB",
            "  BC                             CB",
            "  BBD                           DBB",
            "  BBE                           EBB",
            "  BCE                           ECB",
            "  BBE                           EBB",
            "  BBD                           DBB",
            "  BC                             CB",
            "  BBC                           CBB",
            "   B                             B ",
            "   B                             B ",
            "   BB                           BB ",
            "    B                           B  ",
            "    BB D                     D BB  ",
            "     BB                       BB   ",
            "      BB D                 D BB    ",
            "       BB                   BB     ",
            "        BB                 BB      ",
            "         BBB  C DEEED C  BBB       ",
            "           BBBBCBBCBBCBBBB         ",
            "              BBBBBBBBB            ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BGGBHBGGB            ",
            "               CCCCCCC             ",
            "            CCC DEEED CCC          ",
            "          CC             CC        ",
            "        BCEE             EECB      ",
            "        CE                 EC      ",
            "      BCE                   ECB    ",
            "      CE                     EC    ",
            "     CE                       EC   ",
            "     CE                       EC   ",
            "    C                           C  ",
            "    C                           C  ",
            "    C                           C  ",
            "   C                             C ",
            "   CD                           DC ",
            "  BCE                           ECB",
            "   CE                           EC ",
            "  BCE                           ECB",
            "   CD                           DC ",
            "   C                             C ",
            "    C                           C  ",
            "    C                           C  ",
            "    C                           C  ",
            "     CE                       EC   ",
            "     CE                       EC   ",
            "      CE                     EC    ",
            "      BCE                   ECB    ",
            "        CE                 EC      ",
            "        BCEE             EECB      ",
            "          CC             CC        ",
            "            CCC DEEED CCC          ",
            "               CCCCCCC             ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BGGBBBGGB            ",
            "           BBBBCBBCBBCBBBB         ",
            "         BBB  C DEEED C  BBB       ",
            "        BB                 BB      ",
            "       BB                   BB     ",
            "      BB D                 D BB    ",
            "     BB                       BB   ",
            "    BB D                     D BB  ",
            "    B                           B  ",
            "   BB                           BB ",
            "   B                             B ",
            "   B                             B ",
            "  BBC                           CBB",
            "  BC                             CB",
            "  BBD                           DBB",
            "  BBE                           EBB",
            "  BCE                           ECB",
            "  BBE                           EBB",
            "  BBD                           DBB",
            "  BC                             CB",
            "  BBC                           CBB",
            "   B                             B ",
            "   B                             B ",
            "   BB                           BB ",
            "    B                           B  ",
            "    BB D                     D BB  ",
            "     BB                       BB   ",
            "      BB D                 D BB    ",
            "       BB                   BB     ",
            "        BB                 BB      ",
            "         BBB  C DEEED C  BBB       ",
            "           BBBBCBBCBBCBBBB         ",
            "              BBBBBBBBB            ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BGGGGGGGB            ",
            "               CCBCBCC             ",
            "              C  DDD  C            ",
            "                                   ",
            "        B                   B      ",
            "         D                 D       ",
            "      B                       B    ",
            "       D                     D     ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    C                           C  ",
            "   C                             C ",
            "   C                             C ",
            "  BBD                           DBB",
            "   CD                           DC ",
            "  BBD                           DBB",
            "   C                             C ",
            "   C                             C ",
            "    C                           C  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "       D                     D     ",
            "      B                       B    ",
            "         D                 D       ",
            "        B                   B      ",
            "                                   ",
            "              C  DDD  C            ",
            "               CCBCBCC             ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "              BBGGGGGBB            ",
            "                CCCCC              ",
            "              CC     CC            ",
            "                                   ",
            "                                   ",
            "         F                 F       ",
            "                                   ",
            "       F                     F     ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    C                           C  ",
            "    C                           C  ",
            "   C                             C ",
            "  BC                             CB",
            "   C                             C ",
            "  BC                             CB",
            "   C                             C ",
            "    C                           C  ",
            "    C                           C  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "       F                     F     ",
            "                                   ",
            "         F                 F       ",
            "                                   ",
            "                                   ",
            "              CC     CC            ",
            "                CCCCC              ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "               BBBBBBB             ",
            "                 B B               ",
            "               CCCCCCC             ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    C                           C  ",
            "    C                           C  ",
            "  BBC                           CBB",
            "    C                           C  ",
            "  BBC                           CBB",
            "    C                           C  ",
            "    C                           C  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "               CCCCCCC             ",
            "                 B B               ",
            "                 B B               ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                  C                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "   B                             B ",
            "    C                           C  ",
            "   B                             B ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  C                ",
            "                 B B               ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                  C                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "   B                             B ",
            "    C                           C  ",
            "   B                             B ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  C                ",
            "                 B B               ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "   BB                           BB ",
            "     CE                       EC   ",
            "   BB                           BB ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                  C                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "    B                           B  ",
            "     CE                       EC   ",
            "    B                           B  ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  C                ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "               FDDEDDF             ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "       F                     F     ",
            "       D                     D     ",
            "    BB D                     D BB  ",
            "      CE                     EC    ",
            "    BB D                     D BB  ",
            "       D                     D     ",
            "       F                     F     ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "               FDDEDDF             ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                BBBBB              ",
            "                  C                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "      B                       B    ",
            "     BB                       BB   ",
            "      BCE                   ECB    ",
            "     BB                       BB   ",
            "      B                       B    ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  C                ",
            "                BBBBB              ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "               FDDEDDF             ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "         F                 F       ",
            "         D                 D       ",
            "      BB D                 D BB    ",
            "        CE                 EC      ",
            "      BB D                 D BB    ",
            "         D                 D       ",
            "         F                 F       ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "               FDDEDDF             ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                BBBBB              ",
            "                  C                ",
            "                  E                ",
            "                  E                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "        B                   B      ",
            "       BB                   BB     ",
            "        BCEE             EECB      ",
            "       BB                   BB     ",
            "        B                   B      ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  E                ",
            "                  E                ",
            "                  C                ",
            "                BBBBB              ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "                  C                ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "        BB                 BB      ",
            "          CC             CC        ",
            "        BB                 BB      ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                  C                ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                  C                ",
            "                  C                ",
            "               CCCCCCC             ",
            "              CC     CC            ",
            "              C  DDD  C            ",
            "         BBB  C DEEED C  BBB       ",
            "            CCC DEEED CCC          ",
            "         BBB  C DEEED C  BBB       ",
            "              C  DDD  C            ",
            "              CC     CC            ",
            "               CCCCCCC             ",
            "                  C                ",
            "                  C                ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                CCCCC              ",
            "               CCBCBCC             ",
            "           BBBBCBBCBBCBBBB         ",
            "               CCCCCCC             ",
            "           BBBBCBBCBBCBBBB         ",
            "               CCBCBCC             ",
            "                CCCCC              ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   "
        });

        builder.layer(new String[]{
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "              BBBBBBBBB            ",
            "                 B B               ",
            "              BBBBBBBBB            ",
            "                 B B               ",
            "                 B B               ",
            "                 B B               ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "                                   ",
            "A                                  "
        });


        // Configure the mapping
        builder.whereAny(' ')
               .whereAny('A')
               .whereAny('^')
               .where('B', (state, level, pos) -> 
                   state.is(MultiblockBlocks.ENTROPY_SINGULARITY_CASING.get()) ||
                   state.is(MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get()) ||
                   state.is(MultiblockBlocks.AE_ENERGY_INPUT_HATCH.get()) ||
                   state.is(MultiblockBlocks.ME_MASSIVE_INPUT_HATCH.get()) ||
                   state.is(MultiblockBlocks.ME_MASSIVE_OUTPUT_HATCH.get()) ||
                   state.is(MultiblockBlocks.ME_MASSIVE_FLUID_HATCH.get()) ,
                    Component.translatable("message.ufo.multiblock.singularity_casing_or_hatch"))
               .candidates('B', QuantumPatternPredicates.casingOrHatchCandidates())
               .where('C', MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get())
               .where('D', MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get())
               .where('E', (state, level, pos) -> QuantumPatternPredicates.isAnyFieldGenerator(state),
                    Component.translatable("message.ufo.multiblock.stellar_field_generator"))
               .candidates('E', QuantumPatternPredicates.fieldCandidates())
               .where('F', (state, level, pos) -> 
                   state.is(MultiblockBlocks.ENTROPY_SINGULARITY_CASING.get()) ||
                   state.is(MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get()))
               .where('G', (state, level, pos) -> 
                   state.is(MultiblockBlocks.ENTROPY_SINGULARITY_CASING.get()) ||
                   state.is(MultiblockBlocks.QUANTUM_HYPER_MECHANICAL_CASING.get()) ||
                   state.is(MultiblockBlocks.AE_ENERGY_INPUT_HATCH.get()) ||
                   state.is(MultiblockBlocks.ME_MASSIVE_INPUT_HATCH.get()) ||
                   state.is(MultiblockBlocks.ME_MASSIVE_OUTPUT_HATCH.get()) ||
                   state.is(MultiblockBlocks.ME_MASSIVE_FLUID_HATCH.get()) ,
                    Component.translatable("message.ufo.multiblock.singularity_casing_or_hatch"))
               .candidates('G', QuantumPatternPredicates.casingOrHatchCandidates())
                .where('H', MultiblockBlocks.STELLAR_NEXUS_CONTROLLER.get());

        return builder.shell('B', 'C', 'F', 'G').build();
    }
}
